# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chao Sun
title: Tech Lead (Machine Learning, digital, dynamic system)
email: chaosun.ai@gmail.com
website: https://chaosun-ai.github.io/ModernCV/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: -chao-sun
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: blog
  icon: fas fa-globe
  url: https://chaosun-ai.github.io/blog/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Chao and I'm a Tech Lead working at the [AMRC](https://www.youtube.com/watch?v=PTSDBLr62qI&ab_channel=AMRC) in UK. I've been actively applied machine learning to solve complex engineering problems. At my spare time, I like doing data science competitions on Kaggle to keep myself sharp. And most importantly, I learn new techs super fast!

  I am most skilled in: <mark>Python</mark> and <mark>Machine Learning</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The AMRC
        link: amrc.co.uk
        # link_text: boringcompany.com
        sub_title: Tech Lead (Machine Learning, digital, dynamic system)
        caption: January 2019 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
            
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of British Columbia 
        caption: Vancouver, Canada. 2014 - 2016
        sub_title: Visiting Ph.D. Student, Mechanical Engineering
        quote: >
          Established in 1908, UBC is British Columbia's oldest university. Harvard The university ranks among the top three universities in Canada.
        description: | # this will include new lines to allow paragraphs
          During my time at UBC, I learnt a lot of skills on scientific and engineering research, including system design and modelling, data collection/analysis and paper writing. 
      - layout: left
        title: Shanghai Jiao Tong University
        caption: Shanghai, China. 2010 - 2013
        sub_title: PhD (Co-supervised by UBC) Mechanical Engineering
        quote: >
          Established in 1896, SJTU is is one of China's oldest universities. SJTU is a C9 League university (China's Ivy League).
        description: | # this will include new lines to allow paragraphs
          During my time at SJTU I learnt a lot of key skills, including programming in C++/Matlab, computational geometry, robotics, control system design, computer-aided manufacturing. 

      - layout: left          
        title: Shanghai Jiao Tong University
        caption: Shanghai, China. 2005 - 2009
        sub_title: B.S Mechanical Engineering (Major) Business Management (Minor)
        description: | # this will include new lines to allow paragraphs
          During my time at SJTU I learnt most of my skills that have I have taken through my career. I thoroughly enjoyed my time as university. I was awarded Academic Excellence graduates(2009) because of high academic achievement.    

  - title: Data Science Competition # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indoor Location & Navigation. 
        caption: 2010 - 2013
        sub_title: Solo on Kaggle and won a bronze medal.
        quote: >
          Established in 1636,  is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at  I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
 

  - title: Selected Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Machine Learning
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.  
        title: Digital Twin
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*. 

        title: Robotics
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.            
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
      <iframe width="560" height="315" src="https://www.youtube.com/embed/tjzOzuKQhSM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

      #Look at this cool image  
      #![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
